name: KStaffMode
main: com.kino.kstaffmode.KStaffMode
version: ${project.version}
author: Kino

commands:
  kstaffmode:
    description: Basic command of this plugin.
    aliases: [ksm, kstaffmode, ksmode, kstaffm]
  gm:
    description: Change your gamemode.
    aliases: [gamemode, gm, gamem, gmode]
  staff:
    description: Enable / disable staffmode.
    aliases: [sm, staffmode, mod, modmode, admin, adminmode, h]
  vanish:
    description: Enable / disable vanish.
    aliases: [v, invisibilidad]
  fly:
    description: Enable / disable fly.
    aliases: [volar, vuelo]
  staffchat:
    description: Enable / disable staffchat.
    aliases: [sc, privatechat, modchat, adminchat]
  s:
    description: Teleports someone to your position.
  invsee:
    description: See the inventory of a player