bungee: false
navigatorImpulse: 3
#THIS WILL LET A PLAYER USE THE RANDOMTP ITEM, AND TELEPORT TO A PLAYER THAT IS IN ANOTHER WORLD.
randomTpMultiworld: true
#THIS IS A COMMAND WITHOUT THE "/" THAT WILL BE EXECUTED WHEN A PLAYER DISCONNECTS WHILE FROZEN
frozenDisconnect: "say <player> disconnected frozen!"
staffChatEnabled: true
keepFlyingWhenDisableStaffMode: true
#ID FORMAT: "MATERIAL:DATA" OR "MATERIAL". Example: "STAINED_GLASS_PANE:1" or "ORANGE_STAINED_GLASS_PANE"
#https://helpch.at/docs/1.8/org/bukkit/Material.html -- 1.8
#https://helpch.at/docs/1.12.2/index.html?org/bukkit/Material.html -- 1.12.2
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html -- 1.16.2
staffItems:
  navigator:
    enabled: true
    skull:
      #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
      type: "NULL"
      owner: "Rusheer"
      url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
    id: "COMPASS"
    amount: 1
    name: "&aNavigator"
    lore:
      - "Teleport to the block you are looking at"
    slot: 0
  staffList:
    enabled: true
    skull:
      #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
      type: "NULL"
      owner: "Rusheer"
      url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
    id: "SKULL_ITEM"
    amount: 1
    name: "&2StaffList"
    lore:
      - "List of all staff online"
    slot: 1
  worldEdit:
    enabled: true
    skull:
      #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
      type: "NULL"
      owner: "Rusheer"
      url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
    id: "WOOD_AXE"
    amount: 1
    name: "&aWorldEdit &cWand"
    lore:
      - "The WorldEdit Wand"
    slot: 2
  inspect:
    enabled: true
    skull:
      #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
      type: "NULL"
      owner: "Rusheer"
      url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
    id: "CHEST"
    amount: 1
    name: "&aInspect &bItem"
    lore:
      - "Inspect player's inventory"
    slot: 3
  freeze:
    enabled: true
    skull:
      #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
      type: "NULL"
      owner: "Rusheer"
      url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
    id: "ICE"
    amount: 1
    name: "&bFreeze"
    lore:
      - "Freeze a player"
    slot: 4
  vanish:
    enabled: true
    slot: 6
    vanished:
      skull:
        #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
        type: "NULL"
        owner: "Rusheer"
        url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
      id: "INK_SACK:8"
      amount: 1
      name: "&2Unvanish"
      lore:
        - "Show to other players"
    visible:
      skull:
        #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
        type: "NULL"
        owner: "Rusheer"
        url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
      id: "INK_SACK:10"
      amount: 1
      name: "&2Vanish"
      lore:
        - "Hide to other players"
  fly:
    slot: 7
    enabled: true
    skull:
      #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
      type: "NULL"
      owner: "Rusheer"
      url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
    id: "FEATHER"
    amount: 1
    name: "&eFly"
    lore:
      - "&aToggle fly"
  randomtp:
    slot: 8
    enabled: true
    skull:
      #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
      type: "NULL"
      owner: "Rusheer"
      url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
    id: "EYE_OF_ENDER"
    amount: 1
    name: "&4Random &aTeleport"
    lore:
      - "Teleport to a random player"
inspect:
  title: "&bInspect Menu"
  contents: true
  armor: true
  info:
    enabled: true
    skull:
      #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
      type: "NULL"
      owner: "Rusheer"
      url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
    id: "APPLE"
    amount: 1
    name: "&cInfo"
    lore:
      - "&4Health: <health>"
      - "&aFood: <food>"
      - "&bXp: <xp>"
  gamemode:
    enabled: true
    skull:
      #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
      type: "NULL"
      owner: "Rusheer"
      url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
    id: "DIAMOND_SWORD"
    amount: 1
    name: "&cGamemode: <gm>"
    lore:
      - "&4The gamemode!"
  fly:
    enabled: true
    skull:
      #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
      type: "NULL"
      owner: "Rusheer"
      url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
    id: "FEATHER"
    amount: 1
    name: "&bFlying: <fly>"
    lore:
      - "&cGet if flying!"
  effects:
    enabled: true
    skull:
      #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
      type: "NULL"
      owner: "Rusheer"
      url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
    id: "GLASS_BOTTLE"
    amount: 1
    name: "&ePotion effects"
    format: "&a<name> <level>: &7<duration>"
    #To this field, the plugin will add all potion effects, one line per effect
    lore:
      - "&bEffects:"
  decoration:
    enabled: true
    skull:
      #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
      type: "NULL"
      owner: "Rusheer"
      url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
    id: "STAINED_GLASS_PANE:7"
    amount: 1
    name: ""
    lore:
      - ""
stafflist:
  main:
    title: "&aStaff List &eMenu"
    size: 27
    inStaffMode:
      enabled: true
      skull:
        #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
        type: "NULL"
        owner: "Rusheer"
        url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
      id: "WOOD_AXE"
      amount: 1
      name: "&cAvailable Staff"
      lore:
        - "&eAll players in staff mode"
      slot: 11
    decoration:
      enabled: true
      skull:
        #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
        type: "NULL"
        owner: "Rusheer"
        url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
      id: "STAINED_GLASS_PANE:7"
      amount: 1
      name: ""
      lore:
        - ""
    withoutStaffMode:
      enabled: true
      skull:
        #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
        type: "NULL"
        owner: "Rusheer"
        url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
      id: "REDSTONE_BLOCK"
      amount: 1
      name: "&cStaff Playing"
      lore:
        - "&eAll players without staff mode"
      slot: 15
  inStaffModeMenu:
    title: "&aAvailable Staff &eMenu"
    decoration:
      enabled: true
      skull:
        #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
        type: "NULL"
        owner: "Rusheer"
        url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
      id: "STAINED_GLASS_PANE:7"
      amount: 1
      name: ""
      lore:
        - ""
    pageItem:
      skull:
        #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
        type: "NULL"
        owner: "Rusheer"
        url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
      id: "WATCH"
      name: "&4Page: <page>"
      lore:
        - ""
    nextPage:
      skull:
        #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
        type: "NULL"
        owner: "Rusheer"
        url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
      id: "ARROW"
      amount: 1
      name: "&7Next page"
      lore:
        - ""
    previousPage:
      skull:
        #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
        type: "NULL"
        owner: "Rusheer"
        url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
      id: "ARROW"
      amount: 1
      name: "&7Previous page"
      lore:
        - ""
    heads:
      amount: 1
      name: "<player>"
      lore:
        - "<player> lore!"
  staffPlaying:
    title: "&aStaff Playing &eMenu"
    decoration:
      enabled: true
      skull:
        #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
        type: "NULL"
        owner: "Rusheer"
        url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
      id: "STAINED_GLASS_PANE:7"
      amount: 1
      name: ""
      lore:
        - ""
    pageItem:
      skull:
        #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
        type: "NULL"
        owner: "Rusheer"
        url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
      id: "WATCH"
      name: "&4Page: <page>"
      lore:
        - ""
    nextPage:
      skull:
        #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
        type: "NULL"
        owner: "Rusheer"
        url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
      id: "ARROW"
      name: "&7Next page"
      lore:
        - ""
    previousPage:
      skull:
        #TYPES: "NULL (not skull)", "OWNER (name of a player)", "URL (net.minecraft textures)"
        type: "NULL"
        owner: "Rusheer"
        url: "a7fcf1ddf4c218adbdac828394a114cb83b1a8982f22a2c3038e0685492d8056"
      id: "ARROW"
      amount: 1
      name: "&7Previous page"
      lore:
        - ""
    heads:
      amount: 1
      name: "<player>"
      lore:
        - "<player> lore!"