navigatorImpulse: 3
#THIS WILL LET A PLAYER USE THE RANDOMTP ITEM, AND TELEPORT TO A PLAYER THAT IS IN ANOTHER WORLD.
randomTpMultiworld: true
staffItems:
  navigator:
    enabled: true
    id: 345
    amount: 1
    #If your item doesn't have data, set this to "0"
    data: 0
    name: "&aNavigator"
    lore:
      - "Teleport to the block you are looking at"
    slot: 0
  staffList:
    enabled: true
    id: 397
    amount: 1
    #If your item doesn't have data, set this to "0"
    data: 0
    name: "&2StaffList"
    lore:
      - "List of all staff online"
    slot: 1
  worldEdit:
    enabled: true
    id: 271
    amount: 1
    #If your item doesn't have data, set this to "0"
    data: 0
    name: "&aWorldEdit &cWand"
    lore:
      - "The WorldEdit Wand"
    slot: 2
  inspect:
    enabled: true
    id: 54
    amount: 1
    #If your item doesn't have data, set this to "0"
    data: 0
    name: "&aInspect &bItem"
    lore:
      - "Inspect player's inventory"
    slot: 3
  freeze:
    enabled: true
    id: 79
    amount: 1
    #If your item doesn't have data, set this to "0"
    data: 0
    name: "&bFreeze"
    lore:
      - "Freeze a player"
    slot: 4
  vanish:
    enabled: true
    slot: 6
    vanished:
      id: 351
      amount: 1
      #If your item doesn't have data, set this to "0"
      data: 8
      name: "&2Unvanish"
      lore:
        - "Show to other players"
    visible:
      id: 351
      amount: 1
      #If your item doesn't have data, set this to "0"
      data: 10
      name: "&2Vanish"
      lore:
        - "Hide to other players"
  fly:
    slot: 7
    enabled: true
    id: 288
    amount: 1
    #If your item doesn't have data, set this to "0"
    data: 0
    name: "&eFly"
    lore:
      - "Toggle fly"
  randomtp:
    slot: 8
    enabled: true
    id: 381
    amount: 1
    #If your item doesn't have data, set this to "0"
    data: 0
    name: "&4Random &aTeleport"
    lore:
      - "Teleport to a random player"
